In [1]:
import numpy as np

# let x be true temperature states
xt = np.array([294, 292, 295])

# background temperature states
xb = np.array([298.322, 294.569, 293.819])
eb = np.abs(xb - xt)

# construct background error covariance
sigmab = 5
rhob = 0.5

sigmab_e = sigmab
sigmab_f = sigmab
sigmab_g = sigmab

rho_e_f = rhob
rho_e_g = 0
rho_f_g = rhob

B = np.array([[sigmab_e**2, sigmab_e * sigmab_f * rho_e_f, sigmab_e * sigmab_g * rho_e_g],
              [sigmab_e * sigmab_f * rho_e_f, sigmab_f**2, sigmab_f * sigmab_g * rho_f_g],
              [sigmab_e * sigmab_g * rho_e_g, sigmab_f * sigmab_g * rho_f_g, sigmab_g**2]])

# positions of states in km
i_e, i_f, i_g = 1, 2, 3

# positions of obs in km
i_1, i_2 = 1.3, 2.4

# construct H
H = np.array([(i_f - i_1) / (i_f - i_e), (i_1 - i_e) / (i_f - i_e), 0,
              0, (i_g - i_2) / (i_g - i_f), (i_2 - i_f) / (i_g - i_f)]).reshape(2, 3)

yt = np.dot(H, xt)  # true state in obs space
yb = np.dot(H, xb)  # background state in obs space

# construct observation vector
yo = np.array([294.273, 292.762])

# construct observation error covariance
sigma_1 = 1
sigma_2 = 1
R = np.array([[sigma_1**2, 0],
              [0, sigma_2**2]])

# calculate weights
BHT = np.dot(B, H.T)
HBHT = np.dot(H, np.dot(B, H.T))

# OI equations
W = np.dot(BHT, np.linalg.inv(HBHT + R))
xh = xb + np.dot(W, (yo - yb))
Ph = np.dot((np.eye(3) - np.dot(W, H)), B)

# some diagnostics (chi-square)
Jh = (1/6) * (np.dot((yo - np.dot(H, xh)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xh)) +
              np.dot((xh - xb).T, np.linalg.inv(Ph)).dot(xh - xb))
Jbo = (1/6) * np.dot((yo - np.dot(H, xb)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xb))
Jbb = (1/6) * np.dot((xt - xb).T, np.linalg.inv(B)).dot(xt - xb)
Jb = Jbo + Jbb

Jo = np.dot((yo - np.dot(H, xt)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xt))
Jho = np.dot((yo - np.dot(H, xh)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xh))

print(' Jbo', ' Jbb', ' Jb')
print(Jbo, Jbb, Jb)

print(' Jh', ' Jb', ' Jo', ' Jho')
print(Jh, Jb, Jo, Jho)

eh = np.abs(xh - xt)

print('estimate, truth, prior ')
print(np.vstack([xh, xt, xb]))
print('post error prior error')
print(np.vstack([eh, eb]))
print('estimation error')
print(np.sqrt(np.diag(Ph)))


 Jbo  Jbb  Jb
1.8025937683333133 0.14712299666666673 1.94971676499998
 Jh  Jb  Jo  Jho
1.7373473118116438 1.94971676499998 0.9539730000000722 0.020740634911132573
estimate, truth, prior 
[[295.3059545  292.34246371 293.37730986]
 [294.         292.         295.        ]
 [298.322      294.569      293.819     ]]
post error prior error
[[1.3059545  0.34246371 1.62269014]
 [4.322      2.569      1.181     ]]
estimation error
[1.44040141 1.80735227 2.66696008]


In [2]:
from ipywidgets import interact, interactive, fixed, interact_manual, IntSlider, FloatSlider, Layout, HBox, Label, VBox, RadioButtons
import ipywidgets as widgets

In [19]:

def all(sigmab,rhob):
    # let x be true temperature states
    xt = np.array([294, 292, 295])

    # background temperature states
    xb = np.array([298.322, 294.569, 293.819])
    eb = np.abs(xb - xt)

    # construct background error covariance
    # sigmab = 5
    # rhob = 0.5

    sigmab_e = sigmab
    sigmab_f = sigmab
    sigmab_g = sigmab

    rho_e_f = rhob
    rho_e_g = 0
    rho_f_g = rhob

    B = np.array([[sigmab_e**2, sigmab_e * sigmab_f * rho_e_f, sigmab_e * sigmab_g * rho_e_g],
                [sigmab_e * sigmab_f * rho_e_f, sigmab_f**2, sigmab_f * sigmab_g * rho_f_g],
                [sigmab_e * sigmab_g * rho_e_g, sigmab_f * sigmab_g * rho_f_g, sigmab_g**2]])

    # positions of states in km
    i_e, i_f, i_g = 1, 2, 3

    # positions of obs in km
    i_1, i_2 = 1.3, 2.4

    # construct H
    H = np.array([(i_f - i_1) / (i_f - i_e), (i_1 - i_e) / (i_f - i_e), 0,
                0, (i_g - i_2) / (i_g - i_f), (i_2 - i_f) / (i_g - i_f)]).reshape(2, 3)

    yt = np.dot(H, xt)  # true state in obs space
    yb = np.dot(H, xb)  # background state in obs space

    # construct observation vector
    yo = np.array([294.273, 292.762])

    # construct observation error covariance
    sigma_1 = 1
    sigma_2 = 1
    R = np.array([[sigma_1**2, 0],
                [0, sigma_2**2]])

    # calculate weights
    BHT = np.dot(B, H.T)
    HBHT = np.dot(H, np.dot(B, H.T))

    # OI equations
    W = np.dot(BHT, np.linalg.inv(HBHT + R))
    xh = xb + np.dot(W, (yo - yb))
    Ph = np.dot((np.eye(3) - np.dot(W, H)), B)

    # some diagnostics (chi-square)
    Jh = (1/6) * (np.dot((yo - np.dot(H, xh)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xh)) +
                np.dot((xh - xb).T, np.linalg.inv(Ph)).dot(xh - xb))
    Jbo = (1/6) * np.dot((yo - np.dot(H, xb)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xb))
    Jbb = (1/6) * np.dot((xt - xb).T, np.linalg.inv(B)).dot(xt - xb)
    Jb = Jbo + Jbb

    Jo = np.dot((yo - np.dot(H, xt)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xt))
    Jho = np.dot((yo - np.dot(H, xh)).T, np.linalg.inv(R)).dot(yo - np.dot(H, xh))

    print(f'Jbo: {Jbo:.3f}, Jbb: {Jbb:.3f}, Jb: {Jb:.3f}')

    print(f'Jh : {Jh:.3f}, Jb : {Jb:.3f}, Jo: {Jo:.3f}, Jho: {Jho:.3f}')

    eh = np.abs(xh - xt)

    print()
    print('estimate, truth, prior ')
    print(np.vstack([xh, xt, xb]).round(2))

    print()
    print('post error prior error')
    print(np.vstack([eh, eb]).round(2))
    print()
    print('estimation error')
    print(np.sqrt(np.diag(Ph)).round(2))


s1 = FloatSlider(min=0.0, max=10, step=0.2, value=5, description='Std. Dev of Background ',readout_format='.2f',
           layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})
rho1 = FloatSlider(min=-1, max=1, step=0.05, value=0.5, description='Correlation of Background ',readout_format='.2f',
           layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})


x = interactive(all, sigmab = s1, rhob = rho1)
# output = x.children[-1]
# output.layout.height = '750px'
display(x)


interactive(children=(FloatSlider(value=5.0, description='Std. Dev of Background ', layout=Layout(height='20px…