In [17]:
import numpy as np

# wind speed obs in m/s
yo = np.array([9, 14])
# wind speed guess in m/s
xb = np.array([8, 12])

# case a
stdB = 1.5
stdR = 1
R = stdR**2 * np.eye(2)
B = stdB**2 * np.eye(2)
H = np.array([[1, 0], [0, 1]])
W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
xa = xb + W @ (yo - H @ xb)
Pa = (np.eye(2) - W @ H) @ B
print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb, yo]))

# case b
rhoB = np.array([[1, 0.5], [0.5, 1]])
D = stdB * np.eye(2)
B = D @ rhoB @ D
W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
xa = xb + W @ (yo - H @ xb)
Pa = (np.eye(2) - W @ H) @ B
print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb, yo]))

# case c
B = stdB**2 * np.eye(2)
rhoR = rhoB
D = stdR * np.eye(2)
R = D @ rhoR @ D
W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
xa = xb + W @ (yo - H @ xb)
Pa = (np.eye(2) - W @ H) @ B
print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb, yo]))

# case d
rhoB = np.array([[1, 0.9], [0.9, 1]])
R = stdR**2 * np.eye(2)
D = stdB * np.eye(2)
B = D @ rhoB @ D
W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
xa = xb + W @ (yo - H @ xb)
Pa = (np.eye(2) - W @ H) @ B
print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb, yo]))

# case e
rhoR = np.array([[1, 0.9], [0.9, 1]])
B = stdB**2 * np.eye(2)
D = stdR * np.eye(2)
R = D @ rhoR @ D
W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
xa = xb + W @ (yo - H @ xb)
Pa = (np.eye(2) - W @ H) @ B
print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb, yo]))

# case f
yo = 9
H = np.array([[1, 0]])
B = stdB**2 * np.eye(2)
R = stdR**2 * np.eye(1)
W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
xa = xb + W @ (yo - H @ xb)
Pa = (np.eye(2) - W @ H) @ B
print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb]))

# case g
rhoB = np.array([[1, 0.5], [0.5, 1]])
D = stdB * np.eye(2)
B = D @ rhoB @ D
W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
xa = xb + W @ (yo - H @ xb)
Pa = (np.eye(2) - W @ H) @ B
print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb]))


[[ 8.69230769 13.38461538]
 [ 0.83205029  0.83205029]
 [ 8.         12.        ]
 [ 9.         14.        ]]
[[ 8.89243697 13.42184874]
 [ 0.80648631  0.80648631]
 [ 8.         12.        ]
 [ 9.         14.        ]]
[[ 8.49090909 13.30909091]
 [ 0.80903983  0.80903983]
 [ 8.         12.        ]
 [ 9.         14.        ]]
[[ 9.12380308 13.30747655]
 [ 0.70501773  0.70501773]
 [ 8.         12.        ]
 [ 9.         14.        ]]
[[ 8.33452961 13.29197642]
 [ 0.75028833  0.75028833]
 [ 8.         12.        ]
 [ 9.         14.        ]]
[[ 8.69230769 12.        ]
 [ 0.83205029  1.5       ]
 [ 8.         12.        ]]
[[ 8.69230769 12.34615385]
 [ 0.83205029  1.36402966]
 [ 8.         12.        ]]


In [4]:
from ipywidgets import interact, interactive, fixed, interact_manual, IntSlider, FloatSlider, Layout, HBox, Label, VBox, RadioButtons
import ipywidgets as widgets

In [73]:
def all(obs1,obs2,prior1,prior2,stdB,stdR,rhoR,rhoB):
    
    print('Put negative values to omit any observation............\n')
    # wind speed obs in m/s
    yo = np.array([obs1,obs2])
    # wind speed guess in m/s
    xb = np.array([prior1,prior2])

    if np.any((np.array([obs1,obs2,prior1,prior2]))<0):
        print('One value in obs is missing.')
    
    rhoB_1 = np.array([[1, rhoB], [rhoB, 1]])
    rhoR_1 = np.array([[1, rhoR], [rhoR, 1]])

    H = np.array([[1, 0], [0, 1]])
    D = stdR * np.eye(2)
    R = D @ rhoR_1 @ D

    if obs2<0:
        H = np.array([[1, 0]])
        rhoR_1 = np.array([[1]])
        D = stdR * np.eye(1)
        R = D @ rhoR_1 @ D
        yo = obs1
    elif obs1<0:
        H = np.array([[0, 1]])
        rhoR_1 = np.array([[1]])
        D = stdR * np.eye(1)
        R = D @ rhoR_1 @ D
        yo = obs2

    D = stdB * np.eye(2)
    B = D @ rhoB_1 @ D

    W = B @ H.T @ np.linalg.inv(H @ B @ H.T + R)
    xa = xb + W @ (yo - H @ xb)
    Pa = (np.eye(2) - W @ H) @ B
    print(np.vstack([xa, np.sqrt(np.diag(Pa)), xb]).round(3))


stdB = FloatSlider(min=0.0, max=10, step=0.1, value=1.5, description='Std. Dev of Background ',readout_format='.2f',
           layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})
stdR = FloatSlider(min=0.0, max=10, step=0.1, value=1.0, description='Std. Dev of Observation ',readout_format='.2f',
           layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})

rhoB = FloatSlider(min=-1, max=1, step=0.05, value=0.5, description='Correlation btw Background ',readout_format='.2f',
           layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})
rhoR = FloatSlider(min=-1, max=1, step=0.05, value=0.5, description='Correlation btw Observations ',readout_format='.2f',
           layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})

obs1 = widgets.IntText(
    value=9,
    description='Obs1   :',
    disabled=False,
     layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})

obs2 = widgets.IntText(
    value=14,
    description='Obs1   :',
    disabled=False,
     layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})

prior1 = widgets.IntText(
    value=8,
    description='Prior1 :',
     layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})

prior2 = widgets.IntText(
    value=12,
    description='Prior2 :',
    disabled=False,
     layout=Layout(width='50%', height='20px'), style = {'description_width': '250px'})



x = interactive(all, obs1=obs1,obs2=obs2,prior1=prior1,prior2=prior2,stdB = stdB, stdR = stdR, rhoB = rhoB, rhoR = rhoR)
# output = x.children[-1]
# output.layout.height = '750px'
display(x)


interactive(children=(IntText(value=9, description='Obs1   :', layout=Layout(height='20px', width='50%'), styl…

array([[0.7]])